cities = [ 'bruges' ,'budapest' , 'rome' , 'florence' , 'amsterdam' ,'rio de janeiro' ,'lisbon' ,'prague' ,'paris' ,'venice']
print(cities)
cities.append('seoul')
print(cities)
cities.insert(5 , 'agra')
print(cities)
del cities[4]
print(cities)
cities.pop()
print(cities)
cities.remove('rio de janeiro')
print(cities)
print(sorted(cities))
cities.reverse()
print(cities)
cities.reverse()
print(cities)
cities.sort(reverse = True)
print(cities)
cities.sort()
print(cities)
print( "\t" +  str(len(cities)))
